[build]
  command = "gatsby build"
  publish = "public/"

[functions]
  directory="functions"

[template.environment]
  GATSBY_FLOTIQ_API_KEY="YOUR FLOTIQ API KEY"
  SNIPCART_API_KEY="YOUR SNIPCART API KEY"
